import fs from 'node:fs/promises';
import path from 'node:path';
import pino from 'pino';
import { simpleGit } from 'simple-git';
import { config } from '../../config/index.js';
import { notify } from '../../services/slack-notifier.service.js';
import type { PipelineContext } from '../types.js';

const logger = pino({ name: 'step:apply-and-push', level: config.LOG_LEVEL });

export async function applyAndPushStep(ctx: PipelineContext): Promise<void> {
  if (!ctx.workspacePath || !ctx.codeChanges || !ctx.branchName) {
    throw new Error('workspacePath, codeChanges, and branchName are required');
  }

  const git = simpleGit(ctx.workspacePath);

  for (const change of ctx.codeChanges) {
    const filePath = path.resolve(ctx.workspacePath, change.filePath);

    if (!filePath.startsWith(ctx.workspacePath)) {
      logger.warn(
        { filePath: change.filePath },
        'Skipping file outside workspace (path traversal)',
      );
      continue;
    }

    if (change.action === 'delete') {
      await fs.rm(filePath, { force: true });
      logger.debug({ filePath: change.filePath }, 'Deleted file');
    } else {
      await fs.mkdir(path.dirname(filePath), { recursive: true });
      await fs.writeFile(filePath, change.content, 'utf-8');
      logger.debug({ filePath: change.filePath, action: change.action }, 'Wrote file');
    }
  }

  await git.add('.');

  const commitMessage = `${ctx.request.type}: ${ctx.request.title}\n\n${ctx.request.description}\n\nCloses #${ctx.issueNumber}\n\nGenerated by CodePilot`;
  await git.commit(commitMessage);

  await git.push('origin', ctx.branchName, ['--force']);

  logger.info({ branchName: ctx.branchName }, 'Changes committed and pushed');
  await notify(
    ctx.channelId,
    ctx.threadTs,
    `:rocket: 코드가 \`${ctx.branchName}\` 브랜치에 push 되었습니다.`,
  );
}
