import fs from 'node:fs/promises';
import path from 'node:path';
import { simpleGit } from 'simple-git';
import { validateCodeChanges } from '../../lib/code-validator.js';
import { createLogger } from '../../lib/logger.js';
import { notify } from '../../services/slack-notifier.service.js';
import type { PipelineContext } from '../types.js';

const logger = createLogger('step:apply-and-push');

export async function applyAndPushStep(ctx: PipelineContext): Promise<void> {
  if (!ctx.workspacePath || !ctx.codeChanges || !ctx.branchName) {
    throw new Error('workspacePath, codeChanges, and branchName are required');
  }

  const git = simpleGit(ctx.workspacePath);

  validateCodeChanges(ctx.codeChanges);

  for (const change of ctx.codeChanges) {
    const filePath = path.resolve(ctx.workspacePath, change.filePath);

    if (!filePath.startsWith(ctx.workspacePath)) {
      logger.warn(
        { filePath: change.filePath },
        'Skipping file outside workspace (path traversal)',
      );
      continue;
    }

    try {
      const stat = await fs.lstat(filePath);
      if (stat.isSymbolicLink()) {
        logger.warn({ filePath: change.filePath }, 'Skipping symbolic link');
        continue;
      }
    } catch {
      // File does not exist yet — OK for new file creation
    }

    if (change.action === 'delete') {
      await fs.rm(filePath, { force: true });
      logger.debug({ filePath: change.filePath }, 'Deleted file');
    } else {
      await fs.mkdir(path.dirname(filePath), { recursive: true });
      await fs.writeFile(filePath, change.content, 'utf-8');
      logger.debug({ filePath: change.filePath, action: change.action }, 'Wrote file');
    }
  }

  await git.add('.');

  const commitMessage = `${ctx.request.type}: ${ctx.request.title}\n\n${ctx.request.description}\n\nCloses #${ctx.issueNumber}\n\nGenerated by CodePilot`;
  await git.commit(commitMessage);

  await git.push('origin', ctx.branchName, ['--force']);

  logger.info({ branchName: ctx.branchName }, 'Changes committed and pushed');
  await notify(
    ctx.channelId,
    ctx.threadTs,
    `:rocket: 코드가 \`${ctx.branchName}\` 브랜치에 push 되었습니다.`,
  );
}
