import { config } from '../../config/index.js';
import { createLogger } from '../../lib/logger.js';
import { addAssignees, createPullRequest, findExistingPR, requestReviewers } from '../../services/github.service.js';
import type { PipelineContext } from '../types.js';

const logger = createLogger('step:create-pr');

export async function createPRStep(ctx: PipelineContext): Promise<void> {
  if (!ctx.repoInfo || !ctx.branchName || !ctx.issueNumber) {
    throw new Error('repoInfo, branchName, and issueNumber are required');
  }

  const { owner, repo, defaultBranch } = ctx.repoInfo;

  const existing = await findExistingPR({ owner, repo, head: ctx.branchName });

  if (existing) {
    logger.info({ prNumber: existing.number }, 'Using existing PR');
    ctx.prNumber = existing.number;
    ctx.prUrl = existing.url;
  } else {
    const changesSummary =
      ctx.codeChanges?.map((c) => `- \`${c.filePath}\` (${c.action})`).join('\n') ?? '';

    const pr = await createPullRequest({
      owner,
      repo,
      title: `[CodePilot] ${ctx.request.title}`,
      body: `## ${ctx.request.type}: ${ctx.request.title}\n\n${ctx.request.description}\n\n### Changes\n${changesSummary}\n\nCloses #${ctx.issueNumber}\n\n---\n_Generated by CodePilot_`,
      head: ctx.branchName,
      base: defaultBranch,
    });

    ctx.prNumber = pr.number;
    ctx.prUrl = pr.url;

    // PR assignee 지정 (Slack 요청자)
    if (ctx.githubUsername) {
      try {
        await addAssignees({
          owner,
          repo,
          issueNumber: pr.number,
          assignees: [ctx.githubUsername],
        });
      } catch (err) {
        logger.warn({ err, assignee: ctx.githubUsername }, 'Failed to add PR assignee');
      }
    }

    // 팀 리뷰어 지정
    if (config.GITHUB_REVIEW_TEAM) {
      try {
        await requestReviewers({
          owner,
          repo,
          pullNumber: pr.number,
          teamReviewers: [config.GITHUB_REVIEW_TEAM],
        });
      } catch (err) {
        logger.warn({ err, team: config.GITHUB_REVIEW_TEAM }, 'Failed to request team reviewers');
      }
    }
  }

}
