import pino from 'pino';
import { config } from '../../config/index.js';
import { createPullRequest, findExistingPR } from '../../services/github.service.js';
import { notify } from '../../services/slack-notifier.service.js';
import type { PipelineContext } from '../types.js';

const logger = pino({ name: 'step:create-pr', level: config.LOG_LEVEL });

export async function createPRStep(ctx: PipelineContext): Promise<void> {
  if (!ctx.repoInfo || !ctx.branchName || !ctx.issueNumber) {
    throw new Error('repoInfo, branchName, and issueNumber are required');
  }

  const { owner, repo, defaultBranch } = ctx.repoInfo;

  const existing = await findExistingPR({ owner, repo, head: ctx.branchName });

  if (existing) {
    logger.info({ prNumber: existing.number }, 'Using existing PR');
    ctx.prNumber = existing.number;
    ctx.prUrl = existing.url;
  } else {
    const changesSummary =
      ctx.codeChanges?.map((c) => `- \`${c.filePath}\` (${c.action})`).join('\n') ?? '';

    const pr = await createPullRequest({
      owner,
      repo,
      title: `[CodePilot] ${ctx.request.title}`,
      body: `## ${ctx.request.type}: ${ctx.request.title}\n\n${ctx.request.description}\n\n### Changes\n${changesSummary}\n\nCloses #${ctx.issueNumber}\n\n---\n_Generated by CodePilot_`,
      head: ctx.branchName,
      base: defaultBranch,
    });

    ctx.prNumber = pr.number;
    ctx.prUrl = pr.url;
  }

  await notify(ctx.channelId, ctx.threadTs, `:merged: PR #${ctx.prNumber} 생성 완료\n${ctx.prUrl}`);
}
